"""initial migration

Revision ID: 335a18248ae4
Revises: None
Create Date: 2014-07-18 17:45:55.402000

"""

# revision identifiers, used by Alembic.
revision = '335a18248ae4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
